export {
  postToHost,
  signalReady,
  signalError,
  saveState,
  runHook,
  requestState,
  requestToken,
  setHeaderStatus,
  fetchApi,
  getFileUrl,
  onHostMessage,
  getEmbedParams,
  setHostOrigin,
  addAllowedOrigin,
  parseCollabUrl,
  type WidgetMessage,
  type InitData,
  type EmbedParams,
  type CollabConnection,
} from "./protocol"
